### ISSUE TITLE
Please add RFQuack config

### ISSUE THREAD

**Issue by bazuchan** [joelsernamoreno/EvilCrowRF-V2#18]
There is no schematic so it is not easy to guess pins. Please add build.env for rfquack.

**Comment by bazuchan** [comment]
Finally got delivered working ECRFv2. Did a bit of reverse engineering and make seemingly working config:

```
ECRF=true

RADIOA=CC1101
RADIOA_CS=5
RADIOA_IRQ=2

RADIOB=CC1101
RADIOB_CS=27
RADIOB_IRQ=25

RADIOC=nRF24
RADIOC_CS=15
RADIOC_RST=33
```

**Comment by joelsernamoreno** [comment]
Hello @bazuchan 

I have not had time to test RFQuack with ECRF V2. Can you document the installation for other users?

Thanks
