### ISSUE TITLE
Cannot view the Evil Crow's SSID from cell phones.

### ISSUE THREAD

**Issue by trigat** [joelsernamoreno/EvilCrowRF-V2#29]
I cannot view the Evil Crow's SSID from cell phones.  Is there any issue that may be causing this?  I can see the Evil Crow SSID from any computer and my ESP LilyGo watch.  I cannot however see the SSID from multiple cell phones.  I do not have this issue with other ESP8266/32 Arduino programmed devices that host an AP.  I'm testing this with Android phones since I do not have an Iphone.

**Comment by trigat** [comment]
Another update.  I used the default WiFi settings to upload firmware v1.1.  This allowed me to finally change the AP name to "Evil Crow RF v2."  The name has been stuck on "crow" since last month.  I then immediately uploaded the v1.3.2 sketch with the default .ino.  I copied the SD files over to the SD card after each upload.

I then went to http://192.168.4.1 in the browser and selected the ECRF Config > WiFi Config menu.

I wrote an SSID name of "BlackCrow", updated the passwords to 14 characters in length, and hit Apply.

This worked.  The AP name is now up-to-date.  I guess the AP info should not be updated from within the .ino file.

I'm still not able to view the AP using a phone.  I can view the Crow's AP from Windows and Ubuntu laptops.  Do you happen to know what may be causing this?  I have another ESP8266 and ESP32 board that I can currently connect to using a phone.

**Comment by joelsernamoreno** [comment]
Hello

This is due to the WiFi channel used. You can change this in the firmware and reflash the firmware on the device

This is default, change this
const int wifi_channel = 12

**Comment by trigat** [comment]
Thank you.  I should have tested that.

**Comment by trigat** [comment]
Closing
