### ISSUE TITLE
nrf24 pins 

### ISSUE THREAD

**Issue by daci5455** [joelsernamoreno/EvilCrowRF-V2#31]
Hi i was looking to solder the screen on ecrf v2 but it seems like pins of nrf24 are not what it is by default so could you send me esp32/nrf24 pins

**Comment by joelsernamoreno** [comment]
> Hola, estaba buscando soldar la pantalla en ecrf v2 pero parece que los pines de nrf24 no son lo que son por defecto, ¿podrías enviarme los pines esp32/nrf24?

Hello!

In the repository you have a mousejack sketch. Here are indicated the pins :)
