### ISSUE TITLE
targzfs not declared in this scope ?

### ISSUE THREAD

**Issue by jamesmac10** [joelsernamoreno/EvilCrowRF-V2#32]
Arduino IDE 1.8. All libraries installed (I believe so anyway). I'm attempting to compile and getting the following error:

tarGzFS.begin();
     ^
exit status 1
'tarGzFS' was not declared in this scope

Any ideas anyone? 

BTW Thank you so much to the developer of this Evil Crow V2 project. I just purchased the hardware, it looks like a ton of work has gone into all this! Very excited to try it out. Thank you for any input I can get, in advance.

**Comment by joelsernamoreno** [comment]
Hello!

Can you check that the library is in the arduino library directory?

**Comment by jamesmac10** [comment]
Yes, figured it out already thanks.
