### ISSUE TITLE
radio is off frequency by 50khz

### ISSUE THREAD

**Issue by mikebanz** [joelsernamoreno/EvilCrowRF-V2#34]
More of a hardware issue maybe?

Not sure, I can only find the circuit for the first version.
The cc1101 modules seem to be off frequency by 50khz
Offset looks to be the same for both modules.

Any suggestions?

**Comment by joelsernamoreno** [comment]
Yep, go to the end of the void setup function and change the following:
ELECHOUSE_cc1101.addSpiPin(14, 12, 13, 5, 5, 0);
ELECHOUSE_cc1101.addSpiPin(14, 12, 13, 13, 27, 1);

By:

ELECHOUSE_cc1101.addSpiPin(14, 12, 13, 5, 0);
  ELECHOUSE_cc1101.addSpiPin(14, 12, 13, 13, 27, 1);
ELECHOUSE_cc1101.setModul(0);
ELECHOUSE_cc1101.setClb(1,13,15);
ELECHOUSE_cc1101.setClb(2,16,19);
ELECHOUSE_cc1101.setClb(3,33,38);
ELECHOUSE_cc1101.setClb(4,38,39);
ELECHOUSE_cc1101.setModul(1);
ELECHOUSE_cc1101.setModul(0);
ELECHOUSE_cc1101.setClb(1,13,15);
ELECHOUSE_cc1101.setClb(2,16,19);
ELECHOUSE_cc1101.setClb(3,33,38);
ELECHOUSE_cc1101.setClb(4,38,39);

This should fix the small deviation
