### ISSUE TITLE
Cannot upload

### ISSUE THREAD

**Issue by in4matix** [joelsernamoreno/EvilCrowRF-V2#35]
Stuck at step 15. 

```
/home/daniel/Arduino/EvilCrowRF-V2/firmware/v1.3.2/EvilCrow-RFv2/EvilCrow-RFv2.ino:4:22: fatal error: AsyncTCP.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: AsyncTCP.h: No such file or directory
```

**Comment by joelsernamoreno** [comment]
Hello!

The error indicates that you do not have the Async library downloaded. Read the documentation of the repository and follow the steps indicated in the repository

**Comment by joelsernamoreno** [comment]
You have to download and unzip the library in the directory /home/daniel/Arduino/libraries/

**Comment by in4matix** [comment]
Hi,
Thank you for the reply. Pardon my ignorance, I am fairly new to Linux. Must all of them be cloned into /home/daniel/Arduino/libraries/ ? Or just Async?

**Comment by in4matix** [comment]
Currently I have the all in  /home/daniel/Arduino/

**Comment by joelsernamoreno** [comment]
The libraries directory is /home/daniel/Arduino/libraries/

Here you have to put all the libraries used by Evil Crow RF V2. The firmware (.ino) can be in another location

**Comment by in4matix** [comment]
Thank you very much !
