### ISSUE TITLE
Problem Connecting to Rabbit Labs Evil Crow V2

### ISSUE THREAD

**Issue by Ajekow** [joelsernamoreno/EvilCrowRF-V2#48]
Hello, I flashed all files to the ECV2 through Arduino IDE with no problem and copied the required folders to the SD card and inserted it. 
When I supply it with power the SSID shows up as ESP_CAB869 and is password protected. I have tried the default password multiple times but I have not been able to connect to the ECV2.
Would anyone have a solution to this?
Thanks!

**Comment by joelsernamoreno** [comment]
Try the new firmware version
